name: TrendsUSA Bot
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - sudo apt-get update && sudo apt-get install -y ffmpeg
      - pip install moviepy
      - name: Execute
        run: python3 your_script.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: video-result
          path: output/
